// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3595kCt74dEpedI4GsU0-FR7fa8CdZ9o',
    appId: '1:453370808950:web:50a9228f2a90979487ed57',
    messagingSenderId: '453370808950',
    projectId: 'ai-double-3b497',
    authDomain: 'ai-double-3b497.firebaseapp.com',
    storageBucket: 'ai-double-3b497.firebasestorage.app',
    measurementId: 'G-L97HSHWCK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCF7QMApplC1WArdIoCwIyrme4G00Ycs',
    appId: '1:453370808950:android:f180d3a4aa39340d87ed57',
    messagingSenderId: '453370808950',
    projectId: 'ai-double-3b497',
    storageBucket: 'ai-double-3b497.firebasestorage.app',
  );
}
